name: Metrics

on:
  workflow_dispatch:

jobs:
  general:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: General metrics
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}

          filename: .github/plugins/github-metrics.svg

          base: header
          base_indepth: yes

  repositories:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Featured repository
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}

          filename: .github/plugins/metrics.plugin.repositories.svg

          base: ""

          plugin_repositories: yes
          plugin_repositories_featured: thttp/LinkFlow, thttp/flyio-multi-stack-deploy

  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: .github/plugins/metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  notable:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Notable contributions
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}

          filename: .github/plugins/metrics.plugin.notable.svg

          base: ""

          plugin_notable: yes
  
  rss:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: News from Hacker News
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}

          filename: .github/plugins/metrics.plugin.rss.svg

          base: ""

          plugin_rss: true
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4

  music:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Music playlist
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: .github/plugins/metrics.plugin.music.svg
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/3C0rLVZ8CCsDvtWiWCkf3l?utm_source=generator&theme=0
          plugin_music_limit: 5

  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used languages
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: .github/plugins/metrics.plugin.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_other: yes
