```yml
name: Metrics

on:
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          filename: isocalendar.svg

          token: ${{ secrets.GITHUB_TOKEN }}
          user: thttp

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
```
