name: Metrics

on:
  workflow_dispatch:

jobs:
  general:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: General metrics
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg

  isocalendar:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          user: thttp
          token: ${{ secrets.GITHUB_TOKEN }}

          filename: metrics.plugin.isocalendar.svg

          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
